In [1]:
import torch
print(torch.__version__)

2.7.0+cpu


In [2]:
#scalar 

scalar=torch.tensor(7)
scalar.item()
# item function converts the type to primitve

7

In [3]:
# vector
vector=torch.tensor([7,7])
vector.shape #size of a vector

torch.Size([2])

In [4]:
# creating a random tensor
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.9588, 0.3513, 0.0967, 0.7247],
        [0.7731, 0.1668, 0.3430, 0.6244],
        [0.1292, 0.1762, 0.5402, 0.4851]])

In [5]:
#crearing a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor.shape


torch.Size([224, 224, 3])

## Tensor Operations

In [6]:
#creating a tensor
tensor= torch.tensor([1,2,3])
tensor+10


tensor([11, 12, 13])

### Matrix Multiplication

In [7]:
print(tensor ,"*", tensor)
print(f"Equals {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals tensor([1, 4, 9])


In [8]:

print(f"Matrix multiplication of tensor : {tensor}")
print(torch.matmul(tensor,tensor))

Matrix multiplication of tensor : tensor([1, 2, 3])
tensor(14)


In [9]:
#dealing with shape errors
#intensional error
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

# torch.matmul(tensor_A,tensor_B)

In [10]:
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

torch.matmul(tensor_A,tensor_B.T)
# This operation will work when B is transposed

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [11]:
print(f"Original Shapes : tensor_A = {tensor_A.shape} , tensor_B = {tensor_B.shape}")
print(f"New Shapes : tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multipying : {tensor_A.shape} @ {tensor_B.T.shape}")
print(f"\nOutput:")
print(f"{torch.matmul(tensor_A,tensor_B.T)}")
print(f"\nOutput shape: {torch.matmul(tensor_A,tensor_B.T).shape}")

Original Shapes : tensor_A = torch.Size([3, 2]) , tensor_B = torch.Size([3, 2])
New Shapes : tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multipying : torch.Size([3, 2]) @ torch.Size([2, 3])

Output:
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Tensor aggeration

In [12]:
# defining a tensor
x=torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [13]:
# finding min value
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [14]:
# finding min value
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [15]:
#finding mean 
## Error left intensionally
# x.mean()

In [16]:
#we can convert the data type of tensor using x.type(torch.float32)
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [17]:
# Finding the positional min of a tensor and return the index
x.argmin()

tensor(0)

In [18]:
# Finding the positional max of a tensor and return the index
x.argmax()

tensor(9)

In [19]:
#Add an extra dimension
#reshaping
x_reshaped=x.reshape(10,1)
x_reshaped, x_reshaped.shape

(tensor([[ 0],
         [10],
         [20],
         [30],
         [40],
         [50],
         [60],
         [70],
         [80],
         [90]]),
 torch.Size([10, 1]))

In [20]:
#Add an extra dimension
#reshaping
x_reshaped=x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[ 0, 10],
         [20, 30],
         [40, 50],
         [60, 70],
         [80, 90]]),
 torch.Size([5, 2]))

In [21]:
#Change the view
z=x.view(1,10)
z,z.shape

(tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]), torch.Size([1, 10]))

In [22]:
# view shares the same memory as the original tensor
z[:,0]=5
z,x

(tensor([[ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]]),
 tensor([ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [23]:
#stacking tensors on top of each other
x_stacked=torch.stack([x,x,x,x,x],dim=1)
x_stacked

tensor([[ 5,  5,  5,  5,  5],
        [10, 10, 10, 10, 10],
        [20, 20, 20, 20, 20],
        [30, 30, 30, 30, 30],
        [40, 40, 40, 40, 40],
        [50, 50, 50, 50, 50],
        [60, 60, 60, 60, 60],
        [70, 70, 70, 70, 70],
        [80, 80, 80, 80, 80],
        [90, 90, 90, 90, 90]])

In [24]:
x_reshaped=x_reshaped.reshape([1,10])

In [25]:
#using squeeze method ==> torch.squeeze(tensor)
x_squeezed=torch.squeeze(x_reshaped)

In [26]:
x_reshaped.squeeze().shape

torch.Size([10])

In [27]:
#unsqueesing with formated output
#unsqueesing : adds a single dimension to a tensor
x_unsqueezed=x_squeezed.unsqueeze(dim=0)


print(f" Previous Tensor : {x_squeezed}")
print(f"Shape of  Previous Tensor : {x_squeezed.shape}")


print(f" New Tensor : {x_unsqueezed}")
print(f"Shape of  New Tensor : {x_unsqueezed.shape}")

 Previous Tensor : tensor([ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Shape of  Previous Tensor : torch.Size([10])
 New Tensor : tensor([[ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]])
Shape of  New Tensor : torch.Size([1, 10])


In [28]:
#permute : returns a view (shared memory as that of original tensor) and rearranges the dimension
x_original=torch.rand(size=(224,224,3))

#permute the dimensions
x_permuted=x_original.permute(2,0,1)


print(f"Shape of  Previous Tensor : {x_original.shape}")
print(f"Shape of  New Tensor : {x_permuted.shape}")

Shape of  Previous Tensor : torch.Size([224, 224, 3])
Shape of  New Tensor : torch.Size([3, 224, 224])


In [29]:
# Indexing (Selecting data in tensors)
x=torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [30]:
#indexing on middle bracket (dim=1)
x[0][0] #same asx[0,0]

tensor([1, 2, 3])

In [31]:
#indexing innermost bracket
x[0][1][1]

tensor(5)

In [32]:
# Getting number 9 from tensor using indexing
#mycode 
# x[0,2,2]

In [33]:
# Getting number 3,6,9 from tensor using indexing
#mycode

"""Answer from video"""
x[:,:,2]

tensor([[3, 6, 9]])

In [34]:
# Get all values of the 0 th dimension but only the 1 value of the 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [35]:
# get index 0 of the 0th dimension and all values 0f 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [44]:
import torch
import numpy as np

array=np.arange(1.0, 8.0)
tensor =torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [45]:
#changing value of array
array=array+1

array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [46]:
# tensor to numpy

tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [47]:
#changing the value of tensor
tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
randomTensorA=torch.rand(3,4)
randomTensorB=torch.rand(3,4)

print(randomTensorA)
print(randomTensorB)
print(randomTensorB==randomTensorA)

tensor([[0.9165, 0.9145, 0.0550, 0.3044],
        [0.8352, 0.8222, 0.8944, 0.6620],
        [0.1760, 0.1978, 0.6313, 0.5285]])
tensor([[4.9507e-01, 8.7492e-01, 7.4184e-04, 3.0529e-01],
        [7.7996e-01, 7.3050e-01, 1.5454e-02, 8.1095e-01],
        [4.1198e-01, 1.0513e-01, 8.2728e-01, 7.0962e-01]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [51]:
"""making random but reproduciable tensors"""

#setting random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
randomTensorC=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
randomTensorD=torch.rand(3,4)

print(randomTensorC)
print(randomTensorD)
print(randomTensorC==randomTensorD)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
