In [1]:
import torch
print(torch.__version__)

2.7.0+cpu


In [2]:
#scalar 

scalar=torch.tensor(7)
scalar.item()
# item function converts the type to primitve

7

In [3]:
# vector
vector=torch.tensor([7,7])
vector.shape #size of a vector

torch.Size([2])

In [4]:
# creating a random tensor
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.3970, 0.8388, 0.4523, 0.2154],
        [0.6262, 0.4489, 0.6125, 0.7279],
        [0.0670, 0.7672, 0.6271, 0.5622]])

In [5]:
#crearing a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor.shape


torch.Size([224, 224, 3])

## Tensor Operations

In [ ]:
#creating a tensor
tensor= torch.tensor([1,2,3])
tensor+10


tensor([11, 12, 13])

### Matrix Multiplication

In [7]:
print(tensor ,"*", tensor)
print(f"Equals {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals tensor([1, 4, 9])


In [8]:

print(f"Matrix multiplication of tensor : {tensor}")
print(torch.matmul(tensor,tensor))

Matrix multiplication of tensor : tensor([1, 2, 3])
tensor(14)


In [24]:
#dealing with shape errors
#intensional error
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

# torch.matmul(tensor_A,tensor_B)

In [10]:
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

torch.matmul(tensor_A,tensor_B.T)
# This operation will work when B is transposed

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [11]:
print(f"Original Shapes : tensor_A = {tensor_A.shape} , tensor_B = {tensor_B.shape}")
print(f"New Shapes : tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multipying : {tensor_A.shape} @ {tensor_B.T.shape}")
print(f"\nOutput:")
print(f"{torch.matmul(tensor_A,tensor_B.T)}")
print(f"\nOutput shape: {torch.matmul(tensor_A,tensor_B.T).shape}")

Original Shapes : tensor_A = torch.Size([3, 2]) , tensor_B = torch.Size([3, 2])
New Shapes : tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multipying : torch.Size([3, 2]) @ torch.Size([2, 3])

Output:
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Tensor aggeration

In [12]:
# defining a tensor
x=torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [13]:
# finding min value
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [14]:
# finding min value
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [ ]:
#finding mean 
## Error left intensionally
# x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [16]:
#we can convert the data type of tensor using x.type(torch.float32)
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [17]:
# Finding the positional min of a tensor and return the index
x.argmin()

tensor(0)

In [18]:
# Finding the positional max of a tensor and return the index
x.argmax()

tensor(9)

In [19]:
#Add an extra dimension
#reshaping
x_reshaped=x.reshape(10,1)
x_reshaped, x_reshaped.shape

(tensor([[ 0],
         [10],
         [20],
         [30],
         [40],
         [50],
         [60],
         [70],
         [80],
         [90]]),
 torch.Size([10, 1]))

In [20]:
#Add an extra dimension
#reshaping
x_reshaped=x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[ 0, 10],
         [20, 30],
         [40, 50],
         [60, 70],
         [80, 90]]),
 torch.Size([5, 2]))

In [21]:
#Change the view
z=x.view(1,10)
z,z.shape

(tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]), torch.Size([1, 10]))

In [22]:
# view shares the same memory as the original tensor
z[:,0]=5
z,x

(tensor([[ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]]),
 tensor([ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [23]:
#stacking tensors on top of each other
x_stacked=torch.stack([x,x,x,x,x],dim=1)
x_stacked

tensor([[ 5,  5,  5,  5,  5],
        [10, 10, 10, 10, 10],
        [20, 20, 20, 20, 20],
        [30, 30, 30, 30, 30],
        [40, 40, 40, 40, 40],
        [50, 50, 50, 50, 50],
        [60, 60, 60, 60, 60],
        [70, 70, 70, 70, 70],
        [80, 80, 80, 80, 80],
        [90, 90, 90, 90, 90]])